# Generated by Django 5.2.13 on 2026-05-04 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('leafy', 'Декоративно-лиственное'), ('flowering', 'Цветущее'), ('succulent', 'Суккулент'), ('ampel', 'Ампельное/лиана')], default='leafy', max_length=20, verbose_name='Тип растения'),
        ),
        migrations.AddField(
            model_name='wateringlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто полил'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant', verbose_name='Растение'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего полива'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название растения'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(verbose_name='Частота полива (дней)'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant', verbose_name='Растение'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='watered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время полива'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'plant')},
        ),
    ]
