# Generated by Django 5.2.13 on 2026-05-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_favorite_user_plant_plant_type_wateringlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/', verbose_name='Фото растения'),
        ),
    ]
