# Generated by Django 5.2.13 on 2026-05-12 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='watered_at',
            field=models.DateField(verbose_name='Дата полива'),
        ),
    ]
