# Generated by Django 5.2.13 on 2026-05-12 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_wateringlog_created_at_alter_wateringlog_watered_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wateringlog',
            options={'ordering': ['-watered_at']},
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто полил'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='watered_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата полива'),
        ),
    ]
